var productsNumber = 3;
var inputChar = "a";
var price = "20";
var discount = "20";
var total = "20";
var invalidDate = "2005-04-06";
var dataForAssertName = "sdf";
var street =  "თბილისი, ნუცუბიძის 72, 0177";
var streetAssert = "Street:";

module.exports.invalidDate = invalidDate;
module.exports.price = price;
module.exports.discount = discount;
module.exports.total = total;
module.exports.productsNumber = productsNumber;
module.exports.inputChar = inputChar;
module.exports.dataForAssertName = dataForAssertName;
module.exports.street = street;
module.exports.streetAssert = streetAssert;